### ISSUE TITLE
.prettierc overrides are ignored

### ISSUE THREAD

**Issue by QuentinRoy** [prettier/eslint-plugin-prettier#59]
It seems the plugin ignores prettier's overrides options. E.g. the following `.prettierc` fails for the directory `build_tools`:

```yaml
{
  "trailingComma": "all",
  "overrides": [
    {
      "files": "build_tools/*.js",
      "options": {
        "trailingComma": "es5"
      }
    }
  ]
}
```

**Comment by not-an-aardvark** [comment]
This seems like it might be an issue with `prettier`'s API rather than `eslint-plugin-prettier`. `eslint-plugin-prettier` only uses prettier's API [here](https://github.com/prettier/eslint-plugin-prettier/blob/62085cc01731847d66456e089a7529d25dcb1254/eslint-plugin-prettier.js#L357) to get a config -- it doesn't do any config resolution itself.

**Comment by not-an-aardvark** [comment]
Also, I noticed that you mentioned the name `.prettierc` in the issue, but I think the filename should actually be `.prettierrc`. I'm not sure if this was a typo, but presumably giving the file the wrong name would cause it to get ignored entirely.

**Comment by QuentinRoy** [comment]
The odd thing is that prettier by itself works as expected.
E.g. if I successively run:
```sh
npx prettier --write build_tools/**/*.js  # OK, files modified as expected
npx eslint build_tools/**/*.js  # Nope.
```

**Comment by QuentinRoy** [comment]
If it is useful, here is my `.eslintrc.yml`:

```yaml
root: true
extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - prettier
rules:
  prettier/prettier:
    - error
overrides:
  - files:
    - build_tools/**
    env:
      node: true
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
```
