### ISSUE TITLE
Export a "recommended" configuration

### ISSUE THREAD

**Issue by azz** [prettier/eslint-plugin-prettier#72]
Usually when I set up a project with Prettier I use both `eslint-{plugin,config}-prettier`.

```yaml
---
plugins:
- prettier # eslint-plugin-prettier
extends:
- prettier # eslint-config-prettier
rules:
  prettier/prettier: error # eslint-plugin-prettier
```

What would be great is if this module exported a `"recommended"` configuration that did this for me:

```yaml
---
extends:
- plugin:prettier/recommended
```

Effectively:

```js
module.exports.configs = {
  recommended: {
    extends: ['prettier'],
    plugins: ['prettier'],
    rules: {
      'prettier/prettier': 'error'
    },
  }
}
```

Would such an addition be welcome?
