### ISSUE TITLE
[RFF]support tab as indent

### ISSUE THREAD

**Issue by zhenyulin** [prettier/eslint-plugin-prettier#82]
Using latest versions of `eslint`, `prettier`, `eslint-plugin-prettier`

Here's my .eslintrc.yml

```yaml
---
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  browser: true
  es6: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:jest/recommended
  - prettier
plugins:
  - import
  - jest
  - prettier
rules:
  import/extensions: [warn, {js: never}]
  import/no-extraneous-dependencies: 'off'
  import/no-named-as-default: 'off'
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  prettier/prettier:
    - error
    - {
      singleQuote: true,
      trailingComma: all
    }
```

My team is currently using tab for indentation, and this has been supported by `prettier`: https://github.com/prettier/prettier/pull/1026

Was wondering if there can be an option of { indent: "tab" } or { indentTab: true }?
