### ISSUE TITLE
Test against ESLint 5

### ISSUE THREAD

**Issue by edmorley** [prettier/eslint-plugin-prettier#97]
Hi!

Currently the Travis configuration for this repo does:
```yaml
env:
  - ESLINT_VERSION=latest
  - ESLINT_VERSION=3.15.0
before_script:
  - if [[ $ESLINT_VERSION != "latest" ]]; then
      yarn upgrade "eslint@$ESLINT_VERSION";
fi
```

And in package.json:
```js
  "devDependencies": {
    "eslint": "^3.14.1",
```

At first glance it might appear that `eslint-plugin-prettier` is being tested against "latest" (ie 5.x) and `3.15.0`. However given the `package.json` eslint version is out of date, the plugin is actually only being tested against ESLint `3.19.0` and `3.15.0` - meaning there is no test coverage of 4.x or 5.x.

I would suggest either:
1. Enabling something like https://renovatebot.com/ for this repository (so the `package.json` version is actually "latest"), and renaming `"latest"` in `.travis.yml` to something more accurate, like `"default"`.
2. Changing the `before_script` `.travis.yml` section to remove the conditional, so that it always runs `yarn upgrade "eslint@$ESLINT_VERSION"`, including in the `"latest"` case.

I think option (1) seems preferable, since Renovate would also ensure other dependencies are kept up to date -- plus (2) would be confusing, since someone just looking at `package.json` (and not also `.travis.yml`) might mistakenly think there was still no test coverage of more recent ESLint versions.
